### ISSUE TITLE
Include DRF in your project.

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#1]
You have django-rest-framework installed. But it has not been included in your project to use. Include it in your project so that django can recognize it and it is usable.

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by Siddharth1002** [comment]
Got it!

**Comment by hardikarora2** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by souvenger** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by pankaj1707k** [comment]
@criticic Since, the task is very small, you have only 24 hours to complete it.
