### ISSUE TITLE
Uploading profile picture

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#130]
- Create a directory named **media** in the project's base directory. Create a **profile_pics** directory inside the **media** directory.
- Store a suitable default profile picture inside **media** (Not inside **profile_pics**). It should be a `jpg` file named as `default.jpg`.
- Set-up **MEDIA_ROOT** and **MEDIA_URL** attributes in settings. **MEDIA_URL** must be `/media/`.
- Add a URL pattern for uploading a profile picture for a user. The username should be included in the URL pattern.
- Create a model `Profile` in users app with the following fields:
    - `user`: OnetoOneField with User model (specify `on_delete` attribute)
    - `profile_img`: ImageField with default value `'default.jpg'` and upload location as **profile_pics** directory.
- Create a serializer `ProfileSerializer` for the Profile model. Serialize only the `profile_img` field.
- Create a class-based view to handle a PUT request for uploading a profile picture (`UploadProfilePic`)

**Comment by raghavgoel25** [comment]
claim
