### ISSUE TITLE
Add descriptive information on the project schema

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#131]
Update the README file by adding descriptive information on the project schema i.e., Database tables, their fields along with datatypes, and relationships among them. Represent it in tabular structures.

**Comment by diyawaghmare** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by Ksathwik03** [comment]
Claim

**Comment by pankaj1707k** [comment]
@diyawaghmare Create a page in the Wiki section of the repo instead of adding it to the README.
