### ISSUE TITLE
List of endpoints

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#133]
Add a list of brief information about all endpoints in the project. Follow the following format for each entry. Make it in a tabular structure with first column containing the endpoint and second column containing the request methods allowed for that endpoint.

**Comment by raghavgoel25** [comment]
claim

**Comment by Ksathwik03** [comment]
Claim

**Comment by diyawaghmare** [comment]
claim

**Comment by pankaj1707k** [comment]
@Ksathwik03 Create a page in the Wiki section of the repo instead of doing it in the README.

**Comment by pankaj1707k** [comment]
@Ksathwik03 Since, you cannot make pull requests for Wikis, create a markdown file in project's base directory. Name it as: `Endpoints`. Write everything as specified in the issue description in this file and make a PR for that.
