### ISSUE TITLE
Profile picture retrieval and automatic generation

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#135]
- Create a class-based view that will handle GET request. It will return the Profile object of the User whose username has been passed in the URL. Name it as: `GetUserProfile`
- Add URL pattern to get the Profile (URL must contain the username).
- Set up URL pattern so that on going to the endpoint: `media/profile_pics/<image_name>` (returned by GetUserProfile), we can actually see the image.
- Create signals to automatically create a Profile for a user immediately after he registers.

**Comment by raghavgoel25** [comment]
cl
