### ISSUE TITLE
Create app: qna

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#2]
Create a new django app in your project. Also register the app with the project so that django can recognize it. Name of the app must be: **qna**

**Comment by Siddharth1002** [comment]
Me

**Comment by Siddharth1002** [comment]
Just a small query: While creating virtual environment, should i create the virtual environment outside the given parent directory? 
Like will the tree structure look like this?
A new Masterfolder 
   -> env  
   -> Ask-Us-backend(given directory)

**Comment by pankaj1707k** [comment]
@Siddharth1002 Yeah. You can do that. Although you can create virtual environment anywhere, the parent directory told in the readme is just for easier navigation via command line. Just make sure that you don't create it inside the cloned repo.

**Comment by Siddharth1002** [comment]
> @Siddharth1002 Yeah. You can do that. Although you can create virtual environment anywhere, the parent directory told in the readme is just for easier navigation via command line. Just make sure that you don't create it inside the cloned repo.

Ok!

**Comment by adtoria** [comment]
Claim

**Comment by J-e-e-t** [comment]
claim

**Comment by souvenger** [comment]
claim
