### ISSUE TITLE
Create an api view for Question list and create

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#25]
Add an api view for the Question model. It should act on GET and POST requests.
GET request: Return all Question objects from the database.
POST request: Create a new Question object and add it to the database.

For consistency with new issues to be posted, name the view as `question_list`.

It should be a function based view. You can use `api_view()` decorator provided by DRF.

**Comment by mohitpuri** [comment]
claim
