### ISSUE TITLE
Create api view for Question detail

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#26]
Create a **function-based** api view named `question_detail`. It should handle GET, PUT and DELETE requests.
It should take the `id` (primary key) of a Question object as parameter.
GET: Retrieve the details of the Question object.
PUT: Update the details of the Question object.
DELETE: Delete the Question object.

You can use the `api_view()` decorator provided by DRF.

**Comment by mohitpuri** [comment]
claim
