### ISSUE TITLE
Create an api view for Answer list and create

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#29]
Add a function-based api view for the Answer model that handles GET and POST requests.
GET request: Retrieve all Answer objects from the database.
POST request: Create a new Answer object and add it to the database.

Name the view as: `answer_list`.

**Comment by jalanprakhar** [comment]
claim

**Comment by Ksathwik03** [comment]
Claim

**Comment by raghavgoel25** [comment]
claim

**Comment by rushilpatra** [comment]
Claim
