### ISSUE TITLE
Create 'users' app

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#3]
Create a new django app in the project. Name of the app must be: **users**. Also, register the app with the project so that django can recognize it.

**Comment by deep-ika** [comment]
Thanks for the issue I would like to work on it!!

**Comment by sachin-raghuwanshi** [comment]
claim

**Comment by shlesh** [comment]
claim

**Comment by sachin-raghuwanshi** [comment]
i would like to claim it

**Comment by adtoria** [comment]
Claim

**Comment by J-e-e-t** [comment]
claim

**Comment by souvenger** [comment]
claim

**Comment by codelord09** [comment]
Claim
