### ISSUE TITLE
Modify Answer POST behavior

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#36]
Currently, if we POST a new answer on the URL `http://localhost:8000/question/{q_id}/answer/`, the foreign key field `question` (for question id) is a explicitly required field. However, we want that it should be taken automatically from the URL itself.
Modify the POST request handler of the `answer_list()` view to achieve this.

**Comment by diyawaghmare** [comment]
claim
