### ISSUE TITLE
Create serializer for User registration

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#48]
Create a serializer class `RegisterSerializer` which inherits from `ModelSerializer`. 

Add following custom fields:
- `email` : required
- `password` : required and write-only
- `password2` : required and write-only

Apply appropriate validators to the above fields. (You may use built-in validators)

Fields to be serialized (to be listed in `Meta` class): 
`id`, `username`, `password`, `password2`, `email`, `first_name`, `last_name`

Implement the `validate()` and `create()` methods.

**Comment by raghavgoel25** [comment]
<img width="1440" alt="Screenshot 2021-10-12 at 4 04 52 PM" src="https://user-images.githubusercontent.com/75788719/136941001-f5a751d3-3c33-48ad-88e0-365d45d06ff5.png">
