### ISSUE TITLE
Create a model: Question

### ISSUE THREAD

**Issue by pankaj1707k** [opencodeiiita/Ask-Us-Backend#8]
Create a model in the qna app. Name of the model must be **Question**.
Fields:
- Title
- Description
- Date posted
- Number of answers
- Number of upvotes

Don't add any extra field for now.
It's a good practice to also add a `__str__()` method in your model. So, consider adding it too.

**Comment by adtoria** [comment]
Claim

**Comment by prxtikk-18** [comment]
claim
